package rs.ac.ni.pmf.rwa.tvseries.rest.dto;

public enum ErrorCode
{
	GENERAL_REQUEST_ERROR,
	DUPLICATE_ID,
	DUPLICATE_USER,
	ID_DOSE_NOT_MATCH,
	BAD_EPISODE_NUMBER,
	BAD_RATING,
	TV_SERIES_ALREADY_ON_WATCH_LIST,
	TV_SERIES_NOT_ON_WATCHLIST,
	UNKNOWN_AUTHORITY,
	UNKNOWN_TV_SERIES,
	UNKNOWN_USER,
	UNAUTHORIZED_ACCESS,
	FORBIDDEN_ACCESS,

}